// Referenzliste proteinreicher Lebensmittel (Richtwerte pro 100 g).
// Wird im Protein-Tracker absteigend nach Protein sortiert angezeigt.
// Werte sind gerundete Durchschnitts-/Richtwerte und koennen je nach
// Produkt/Marke abweichen.
export type ProteinFood = {
  name: string;
  protein: number; // g pro 100 g
  kcal: number; // kcal pro 100 g
  group: string; // Kategorie (nur zur Info)
};

export const PROTEIN_FOODS: ProteinFood[] = [
  // Pulver / getrocknet / konzentriert
  { name: 'Whey Protein Isolat', protein: 90, kcal: 373, group: 'Protein-Pulver' },
  { name: 'Sojaprotein-Isolat', protein: 88, kcal: 375, group: 'Protein-Pulver' },
  { name: 'Whey Protein Konzentrat', protein: 80, kcal: 400, group: 'Protein-Pulver' },
  { name: 'Casein-Protein', protein: 80, kcal: 370, group: 'Protein-Pulver' },
  { name: 'Erbsenprotein-Pulver', protein: 80, kcal: 400, group: 'Protein-Pulver' },
  { name: 'Spirulina (getrocknet)', protein: 57, kcal: 290, group: 'Sonstiges' },
  { name: 'Sojaschnetzel (TVP, trocken)', protein: 50, kcal: 345, group: 'Pflanzlich' },
  { name: 'Hanfprotein-Pulver', protein: 50, kcal: 380, group: 'Protein-Pulver' },
  { name: 'Mandelmehl (entoelt)', protein: 50, kcal: 400, group: 'Nuesse & Samen' },
  { name: 'Beef Jerky (Trockenfleisch)', protein: 50, kcal: 410, group: 'Fleisch' },
  { name: 'Bierhefe (getrocknet)', protein: 48, kcal: 325, group: 'Sonstiges' },
  { name: 'Lupinenmehl', protein: 40, kcal: 370, group: 'Pflanzlich' },
  { name: 'Buendnerfleisch', protein: 38, kcal: 180, group: 'Fleisch' },
  { name: 'Parmesan', protein: 38, kcal: 431, group: 'Kaese' },
  { name: 'Sojabohnen (getrocknet)', protein: 36, kcal: 446, group: 'Huelsenfruechte' },

  // Kaese
  { name: 'Grana Padano', protein: 33, kcal: 398, group: 'Kaese' },
  { name: 'Proteinriegel', protein: 33, kcal: 350, group: 'Snacks' },
  { name: 'Manchego', protein: 32, kcal: 390, group: 'Kaese' },
  { name: 'Harzer Kaese', protein: 30, kcal: 125, group: 'Kaese' },
  { name: 'Kuerbiskerne', protein: 30, kcal: 559, group: 'Nuesse & Samen' },
  { name: 'Bergkaese', protein: 29, kcal: 400, group: 'Kaese' },
  { name: 'Emmentaler', protein: 28, kcal: 380, group: 'Kaese' },
  { name: 'Pecorino', protein: 28, kcal: 387, group: 'Kaese' },
  { name: 'Gruyere', protein: 27, kcal: 413, group: 'Kaese' },
  { name: 'Edamer', protein: 26, kcal: 330, group: 'Kaese' },
  { name: 'Gouda', protein: 25, kcal: 356, group: 'Kaese' },
  { name: 'Cheddar', protein: 25, kcal: 402, group: 'Kaese' },
  { name: 'Appenzeller', protein: 25, kcal: 390, group: 'Kaese' },
  { name: 'Tilsiter', protein: 25, kcal: 340, group: 'Kaese' },
  { name: 'Mozzarella', protein: 18, kcal: 250, group: 'Kaese' },
  { name: 'Camembert', protein: 20, kcal: 299, group: 'Kaese' },
  { name: 'Feta', protein: 14, kcal: 264, group: 'Kaese' },
  { name: 'Huettenkaese (Cottage Cheese)', protein: 13, kcal: 98, group: 'Kaese' },
  { name: 'Ricotta', protein: 11, kcal: 174, group: 'Kaese' },
  { name: 'Frischkaese', protein: 6, kcal: 250, group: 'Kaese' },

  // Fleisch & Wurst
  { name: 'Haehnchenbrust', protein: 31, kcal: 165, group: 'Fleisch' },
  { name: 'Putenbrust', protein: 30, kcal: 135, group: 'Fleisch' },
  { name: 'Hirschfleisch (Reh)', protein: 30, kcal: 120, group: 'Fleisch' },
  { name: 'Serranoschinken', protein: 30, kcal: 240, group: 'Fleisch' },
  { name: 'Bisonfleisch', protein: 28, kcal: 140, group: 'Fleisch' },
  { name: 'Wildschwein', protein: 28, kcal: 120, group: 'Fleisch' },
  { name: 'Rindersteak', protein: 27, kcal: 250, group: 'Fleisch' },
  { name: 'Putenhackfleisch', protein: 27, kcal: 150, group: 'Fleisch' },
  { name: 'Rinderfilet', protein: 27, kcal: 206, group: 'Fleisch' },
  { name: 'Schweinefilet', protein: 26, kcal: 143, group: 'Fleisch' },
  { name: 'Rinderhack (mager)', protein: 26, kcal: 250, group: 'Fleisch' },
  { name: 'Lammkotelett', protein: 25, kcal: 258, group: 'Fleisch' },
  { name: 'Corned Beef', protein: 25, kcal: 180, group: 'Fleisch' },
  { name: 'Landjaeger', protein: 25, kcal: 450, group: 'Fleisch' },
  { name: 'Haehnchenschenkel', protein: 24, kcal: 209, group: 'Fleisch' },
  { name: 'Kalbsschnitzel', protein: 24, kcal: 170, group: 'Fleisch' },
  { name: 'Entenbrust', protein: 23, kcal: 200, group: 'Fleisch' },
  { name: 'Salami', protein: 22, kcal: 350, group: 'Fleisch' },
  { name: 'Kabanossi', protein: 22, kcal: 440, group: 'Fleisch' },
  { name: 'Kaninchen', protein: 21, kcal: 170, group: 'Fleisch' },
  { name: 'Kasseler', protein: 20, kcal: 130, group: 'Fleisch' },
  { name: 'Kochschinken', protein: 18, kcal: 110, group: 'Fleisch' },
  { name: 'Putenaufschnitt', protein: 18, kcal: 100, group: 'Fleisch' },
  { name: 'Bratwurst', protein: 13, kcal: 300, group: 'Fleisch' },
  { name: 'Leberkaese', protein: 13, kcal: 280, group: 'Fleisch' },
  { name: 'Mortadella', protein: 12, kcal: 300, group: 'Fleisch' },

  // Fisch & Meeresfruechte
  { name: 'Sardellen (Anchovis)', protein: 29, kcal: 210, group: 'Fisch' },
  { name: 'Lachsschinken', protein: 27, kcal: 110, group: 'Fisch' },
  { name: 'Thunfisch (Konserve, Wasser)', protein: 26, kcal: 116, group: 'Fisch' },
  { name: 'Sardinen', protein: 25, kcal: 208, group: 'Fisch' },
  { name: 'Raeucherlachs', protein: 25, kcal: 180, group: 'Fisch' },
  { name: 'Garnelen', protein: 24, kcal: 99, group: 'Fisch' },
  { name: 'Miesmuscheln', protein: 24, kcal: 172, group: 'Fisch' },
  { name: 'Thunfisch (frisch)', protein: 23, kcal: 144, group: 'Fisch' },
  { name: 'Heilbutt', protein: 21, kcal: 110, group: 'Fisch' },
  { name: 'Lachs', protein: 20, kcal: 208, group: 'Fisch' },
  { name: 'Forelle', protein: 20, kcal: 119, group: 'Fisch' },
  { name: 'Makrele', protein: 19, kcal: 205, group: 'Fisch' },
  { name: 'Zander', protein: 19, kcal: 83, group: 'Fisch' },
  { name: 'Kabeljau', protein: 18, kcal: 82, group: 'Fisch' },
  { name: 'Seelachs', protein: 18, kcal: 81, group: 'Fisch' },
  { name: 'Hering', protein: 18, kcal: 210, group: 'Fisch' },
  { name: 'Scholle', protein: 17, kcal: 86, group: 'Fisch' },
  { name: 'Tintenfisch (Calamari)', protein: 16, kcal: 92, group: 'Fisch' },
  { name: 'Surimi', protein: 8, kcal: 95, group: 'Fisch' },

  // Eier
  { name: 'Huehnerei', protein: 13, kcal: 155, group: 'Eier' },
  { name: 'Ruehrei', protein: 13, kcal: 170, group: 'Eier' },
  { name: 'Wachtelei', protein: 13, kcal: 158, group: 'Eier' },
  { name: 'Eiklar (Eiweiss)', protein: 11, kcal: 52, group: 'Eier' },

  // Milchprodukte / Quark / Joghurt
  { name: 'Magerquark', protein: 12, kcal: 67, group: 'Milchprodukte' },
  { name: 'Speisequark (20%)', protein: 12, kcal: 110, group: 'Milchprodukte' },
  { name: 'Skyr', protein: 11, kcal: 63, group: 'Milchprodukte' },
  { name: 'Proteinjoghurt', protein: 10, kcal: 60, group: 'Milchprodukte' },
  { name: 'Griechischer Joghurt (10%)', protein: 9, kcal: 115, group: 'Milchprodukte' },
  { name: 'Naturjoghurt (1,5%)', protein: 4, kcal: 50, group: 'Milchprodukte' },
  { name: 'Milch (3,5%)', protein: 3.4, kcal: 64, group: 'Milchprodukte' },
  { name: 'Buttermilch', protein: 3.5, kcal: 37, group: 'Milchprodukte' },
  { name: 'Kefir', protein: 3.3, kcal: 52, group: 'Milchprodukte' },

  // Huelsenfruechte & Soja
  { name: 'Linsen (getrocknet)', protein: 24, kcal: 353, group: 'Huelsenfruechte' },
  { name: 'Kidneybohnen (getrocknet)', protein: 24, kcal: 333, group: 'Huelsenfruechte' },
  { name: 'Erbsen (getrocknet)', protein: 23, kcal: 341, group: 'Huelsenfruechte' },
  { name: 'Weisse Bohnen (getrocknet)', protein: 21, kcal: 333, group: 'Huelsenfruechte' },
  { name: 'Kichererbsen (getrocknet)', protein: 19, kcal: 364, group: 'Huelsenfruechte' },
  { name: 'Seitan', protein: 25, kcal: 130, group: 'Pflanzlich' },
  { name: 'Tempeh', protein: 19, kcal: 190, group: 'Pflanzlich' },
  { name: 'Raeuchertofu', protein: 16, kcal: 150, group: 'Pflanzlich' },
  { name: 'Quorn', protein: 15, kcal: 110, group: 'Pflanzlich' },
  { name: 'Tofu (natur)', protein: 12, kcal: 127, group: 'Pflanzlich' },
  { name: 'Edamame', protein: 11, kcal: 121, group: 'Huelsenfruechte' },
  { name: 'Kichererbsen (gekocht)', protein: 9, kcal: 164, group: 'Huelsenfruechte' },
  { name: 'Linsen (gekocht)', protein: 9, kcal: 116, group: 'Huelsenfruechte' },
  { name: 'Schwarze Bohnen (gekocht)', protein: 9, kcal: 132, group: 'Huelsenfruechte' },

  // Nuesse & Samen
  { name: 'Erdnuesse', protein: 26, kcal: 567, group: 'Nuesse & Samen' },
  { name: 'Erdnussbutter', protein: 25, kcal: 588, group: 'Nuesse & Samen' },
  { name: 'Mandeln', protein: 21, kcal: 579, group: 'Nuesse & Samen' },
  { name: 'Sonnenblumenkerne', protein: 21, kcal: 584, group: 'Nuesse & Samen' },
  { name: 'Mandelmus', protein: 21, kcal: 614, group: 'Nuesse & Samen' },
  { name: 'Pistazien', protein: 20, kcal: 560, group: 'Nuesse & Samen' },
  { name: 'Leinsamen', protein: 18, kcal: 534, group: 'Nuesse & Samen' },
  { name: 'Cashewkerne', protein: 18, kcal: 553, group: 'Nuesse & Samen' },
  { name: 'Sesam', protein: 17, kcal: 573, group: 'Nuesse & Samen' },
  { name: 'Chiasamen', protein: 17, kcal: 486, group: 'Nuesse & Samen' },
  { name: 'Walnuesse', protein: 15, kcal: 654, group: 'Nuesse & Samen' },
  { name: 'Haselnuesse', protein: 15, kcal: 628, group: 'Nuesse & Samen' },
  { name: 'Pinienkerne', protein: 14, kcal: 673, group: 'Nuesse & Samen' },
  { name: 'Paranuesse', protein: 14, kcal: 659, group: 'Nuesse & Samen' },

  // Getreide & Brot
  { name: 'Dinkel (Korn)', protein: 15, kcal: 338, group: 'Getreide' },
  { name: 'Quinoa (roh)', protein: 14, kcal: 368, group: 'Getreide' },
  { name: 'Amaranth', protein: 14, kcal: 371, group: 'Getreide' },
  { name: 'Haferflocken', protein: 13, kcal: 372, group: 'Getreide' },
  { name: 'Couscous (roh)', protein: 13, kcal: 376, group: 'Getreide' },
  { name: 'Buchweizen', protein: 13, kcal: 343, group: 'Getreide' },
  { name: 'Vollkornnudeln (roh)', protein: 13, kcal: 350, group: 'Getreide' },
  { name: 'Hirse', protein: 11, kcal: 378, group: 'Getreide' },
  { name: 'Vollkornbrot', protein: 9, kcal: 220, group: 'Getreide' },
  { name: 'Roggenbrot', protein: 7, kcal: 220, group: 'Getreide' },
];
