// Motivationssprüche für die tägliche Benachrichtigung (rotierend, 1x pro Tag).
// 110+ kurze, motivierende Zeilen (Fitness, Disziplin, Mindset).
export const MOTIVATION_QUOTES: string[] = [
  'Jeder Tag ist eine neue Chance, stärker zu werden.',
  'Disziplin schlägt Motivation – fang einfach an.',
  'Kleine Schritte jeden Tag führen zu großen Ergebnissen.',
  'Dein einziger Gegner bist du selbst von gestern.',
  'Aufgeben gibt es nicht – nur kurze Pausen.',
  'Schweiß ist nur Fett, das weint.',
  'Du musst nicht perfekt sein, nur besser als gestern.',
  'Fortschritt statt Perfektion.',
  'Der schwerste Schritt ist der zur Tür hinaus.',
  'Dein Körper schafft fast alles – überzeuge deinen Kopf.',
  'Erfolg ist die Summe kleiner Anstrengungen, Tag für Tag.',
  'Mach es jetzt – „später" wird oft „nie".',
  'Stark wirst du nicht im Komfort, sondern an deinen Grenzen.',
  'Glaub an dich, auch wenn es gerade niemand sonst tut.',
  'Jede Wiederholung bringt dich näher ans Ziel.',
  'Müdigkeit vergeht, Stolz bleibt.',
  'Du bist stärker, als du denkst.',
  'Heute ist der perfekte Tag, um anzufangen.',
  'Ausreden verbrennen keine Kalorien.',
  'Konstanz ist wichtiger als Intensität.',
  'Mach es für die Person, die du werden willst.',
  'Der Schmerz von heute ist die Kraft von morgen.',
  'Niemand hat es bereut, trainiert zu haben.',
  'Wachstum beginnt am Ende der Komfortzone.',
  'Sei stolz auf jeden Schritt, den du machst.',
  'Dein Tempo ist genau richtig – Hauptsache, du bleibst dran.',
  'Ein Workout ist nie umsonst.',
  'Träume groß, fang klein an, leg jetzt los.',
  'Du gegen dich – und du gewinnst.',
  'Wenn es schwer wird, fängt es an zu zählen.',
  'Investiere in deinen Körper – du wohnst ein Leben lang darin.',
  'Heute schwitzen, morgen strahlen.',
  'Motivation bringt dich in Gang, Gewohnheit hält dich am Laufen.',
  'Mach den ersten Satz – der Rest kommt von allein.',
  'Erfolg ist kein Zufall, sondern harte Arbeit.',
  'Es zählt nicht, wie langsam du gehst, solange du nicht stehen bleibst.',
  'Dein zukünftiges Ich wird dir danken.',
  'Stärke wächst, wenn du weitermachst, obwohl du aufhören willst.',
  'Jeder Profi war einmal ein Anfänger.',
  'Du brauchst keine Erlaubnis, um an dir zu arbeiten.',
  'Trainiere deinen Geist genauso wie deinen Körper.',
  'Kleine Gewohnheiten, große Veränderung.',
  'Heute ein bisschen besser als gestern – das reicht.',
  'Vergleiche dich mit dir selbst, nicht mit anderen.',
  'Der beste Zeitpunkt war gestern, der zweitbeste ist jetzt.',
  'Steh auf, mach weiter, werde stärker.',
  'Wer kämpft, kann verlieren – wer nicht kämpft, hat schon verloren.',
  'Deine Grenzen sind oft nur in deinem Kopf.',
  'Bleib hungrig, bleib bescheiden, bleib dran.',
  'Fitness ist kein Ziel, sondern ein Lebensstil.',
  'Schaff dir Routinen, dann brauchst du keine Motivation.',
  'Solange du nicht aufgibst, ist kein Tag verloren.',
  'Du hast es heute schon einmal geschafft aufzustehen – mach weiter.',
  'Lieber unperfekt angefangen als perfekt aufgeschoben.',
  'Energie bekommst du, indem du sie einsetzt.',
  'Sei geduldig mit dir – Ergebnisse brauchen Zeit.',
  'Dein Wille ist dein stärkster Muskel.',
  'Mach es trotzdem – besonders, wenn du keine Lust hast.',
  'Tu heute, was andere nicht wollen, und lebe morgen, wie andere nicht können.',
  'Jede gesunde Entscheidung zählt.',
  'Du bist nur eine Gewohnheit von deinem besten Selbst entfernt.',
  'Fall siebenmal hin, steh achtmal auf.',
  'Schritt für Schritt wird auch der weiteste Weg machbar.',
  'Vertrau dem Prozess.',
  'Stärke ist die Fähigkeit, weiterzumachen.',
  'Dein Einsatz heute formt dein Morgen.',
  'Hör auf deinen Körper, aber lass dich nicht von Faulheit täuschen.',
  'Mach das Beste aus dem, was du heute hast.',
  'Selbstdisziplin ist Selbstliebe.',
  'Du musst anfangen, um groß zu werden.',
  'Bleib konsequent, auch wenn niemand zuschaut.',
  'Du baust dich Stück für Stück – jede Einheit zählt.',
  'Gewinner sind Verlierer, die noch einmal aufgestanden sind.',
  'Mach es für deine Gesundheit, nicht nur für den Spiegel.',
  'Heute ist dein Tag – nutze ihn.',
  'Sei stärker als deine stärkste Ausrede.',
  'Erfolg beginnt mit dem Entschluss, es zu versuchen.',
  'Auch langsame Fortschritte sind Fortschritte.',
  'Dranbleiben ist das ganze Geheimnis.',
  'Du wirst nie wissen, was du schaffen kannst, wenn du es nicht versuchst.',
  'Mach deinen Körper zu einem Ort, in dem deine Seele gern wohnt.',
  'Jeder Schweißtropfen ist ein Schritt nach vorn.',
  'Konzentrier dich auf das, was du beeinflussen kannst.',
  'Der Weg ist hart, aber das Ziel ist es wert.',
  'Verändere deine Gewohnheiten und du veränderst dein Leben.',
  'Sei heute der Grund, warum du morgen stolz bist.',
  'Stark sein heißt, immer wieder aufzustehen.',
  'Glaube an deinen Fortschritt, auch wenn du ihn noch nicht siehst.',
  'Mach den Tag zu deinem.',
  'Es gibt kein „kann nicht", nur „noch nicht".',
  'Beweg dich – dein Kopf wird es dir danken.',
  'Du hast nur einen Körper. Behandle ihn gut.',
  'Heute hart, morgen stolz.',
  'Verschwende keinen Tag, an dem du besser werden könntest.',
  'Deine Disziplin von heute ist deine Freiheit von morgen.',
  'Lass Taten sprechen.',
  'Bleib ruhig und mach einfach weiter.',
  'Was du heute säst, erntest du morgen.',
  'Sei die beste Version von dir.',
  'Ein kleiner Fortschritt ist immer noch ein Fortschritt.',
  'Niemand kann es für dich tun – aber du kannst es.',
  'Vertraue darauf, dass sich deine Mühe auszahlt.',
  'Steh für dich und deine Ziele ein.',
  'Gedanken bremsen, Taten bewegen – mach einfach.',
  'Auch heute zählt.',
  'Werde 1 % besser – jeden Tag.',
  'Stärke kommt von innen.',
  'Du bist auf dem richtigen Weg – bleib dran.',
  'Gib deinem Tag einen guten Grund.',
  'Jeder Tag, an dem du dranbleibst, ist ein Sieg.',
  'Erschaffe die Gewohnheiten, die dein Ziel verlangen.',
  'Hart zu dir zu sein zahlt sich leise aus.',
  'Heute zählt mehr als das perfekte Morgen.',
  'Bewegung ist ein Geschenk an dich selbst.',
];
