-- ============================================================================
--  Migration 008 - Mehr Uebungen je Muskelgruppe, >= 5 je Umgebung
--  HINWEIS: Diese Migration legt KEINE GIF-Spalte an. Die animierten GIFs werden
--  client-seitig ueber app/lib/exerciseMedia.ts anhand des Uebungs-NAMENS aufgeloest
--  und von ExerciseDB geladen. Hier werden nur Uebungs-Datensaetze eingefuegt.
--  Im Supabase SQL Editor ausfuehren. Idempotent (fuegt nur fehlende ein). Optional (nur Seeds).
-- ============================================================================
insert into public.exercises (name, difficulty, equipment, primary_muscle_id, description, instructions)
select e.name, e.difficulty, e.equipment, m.id, e.description, e.instructions
from (values
  ('Schrägbank-Kurzhanteldrücken','intermediate','dumbbell','chest','Oberes Brustdrücken mit Kurzhanteln auf der Schrägbank.','1. Schrägbank ca. 30 Grad, Kurzhanteln auf Brusthöhe. 2. Nach oben drücken. 3. Kontrolliert senken.'),
  ('Butterfly (Maschine)','beginner','machine','chest','Geführte Brust-Isolation an der Butterfly-Maschine.','1. Unterarme an die Polster. 2. Vor der Brust zusammenführen. 3. Langsam öffnen.'),
  ('Negativ-Bankdrücken','intermediate','barbell','chest','Bankdrücken auf der Negativbank, betont die untere Brust.','1. Auf der Negativbank liegen. 2. Stange zur unteren Brust. 3. Hochdrücken.'),
  ('T-Bar-Rudern','intermediate','barbell','back','Ruderübung für den mittleren Rücken mit der T-Bar.','1. Vorgebeugt, Griff fassen. 2. Zum Bauch ziehen. 3. Kontrolliert senken.'),
  ('Kurzhantel-Überzüge','intermediate','dumbbell','back','Überzug für Brustkorb und breiten Rücken.','1. Quer auf der Bank. 2. Kurzhantel hinter den Kopf senken. 3. Zurückziehen.'),
  ('Klimmzug breit','advanced','bodyweight','back','Klimmzug mit breitem Griff, starker Lat-Fokus.','1. Breiter Obergriff. 2. Hochziehen bis Kinn über die Stange. 3. Absenken.'),
  ('Hyperextensions','beginner','bodyweight','back','Stärkt unteren Rücken und Gesäß.','1. Hüfte auf dem Polster. 2. Oberkörper anheben. 3. Kontrolliert senken.'),
  ('Aufrechtes Rudern','intermediate','barbell','shoulders','Zugübung für seitliche Schulter und Trapez.','1. Stange eng greifen. 2. Bis Brusthöhe ziehen, Ellbogen hoch. 3. Senken.'),
  ('Kabel-Seitheben','beginner','cable','shoulders','Seitheben am Kabel mit konstanter Spannung.','1. Unteres Kabel seitlich greifen. 2. Bis Schulterhöhe heben. 3. Senken.'),
  ('Schulterdrücken (Maschine)','beginner','machine','shoulders','Geführtes Schulterdrücken an der Maschine.','1. Griffe auf Schulterhöhe. 2. Nach oben drücken. 3. Kontrolliert senken.'),
  ('Schrägbank-Curls','intermediate','dumbbell','biceps','Bizeps-Curls auf der Schrägbank für mehr Dehnung.','1. Zurückgelehnt sitzen, Arme hängen. 2. Hochcurlen. 3. Langsam senken.'),
  ('Scott-Curls','beginner','machine','biceps','Bizeps-Isolation auf der Scott-Bank.','1. Oberarme auf dem Polster. 2. Hochcurlen. 3. Kontrolliert senken.'),
  ('Umgekehrte Curls','beginner','barbell','biceps','Curls im Obergriff für Bizeps und Unterarm.','1. Stange im Obergriff. 2. Hochcurlen. 3. Senken.'),
  ('Überkopf-Trizeps (Kabel)','intermediate','cable','triceps','Überkopf-Trizepsstrecken am Kabel.','1. Seil über dem Kopf fassen. 2. Nach oben strecken. 3. Beugen.'),
  ('Bankdrücken eng','intermediate','barbell','triceps','Enges Bankdrücken mit Trizepsfokus.','1. Stange eng greifen. 2. Zur Brust senken, Ellbogen am Körper. 3. Hochdrücken.'),
  ('Diamant-Liegestütze','intermediate','bodyweight','triceps','Liegestütze mit Diamant-Handstellung, starker Trizepsreiz.','1. Hände bilden ein Dreieck. 2. Absenken. 3. Hochdrücken.'),
  ('Sit-up','beginner','bodyweight','abs','Klassischer Sit-up für die Bauchmuskeln.','1. Rückenlage, Knie gebeugt. 2. Oberkörper ganz aufrichten. 3. Senken.'),
  ('Cable Crunch','intermediate','cable','abs','Bauchpresse am Kabel mit Zusatzgewicht.','1. Kniend, Seil hinter dem Kopf. 2. Oberkörper einrollen. 3. Zurück.'),
  ('Beinheben hängend','advanced','bodyweight','abs','Unterer Bauch, an der Stange hängend.','1. An der Stange hängen. 2. Gestreckte Beine heben. 3. Langsam senken.'),
  ('Frontkniebeuge','advanced','barbell','legs','Kniebeuge mit Stange vorn, betont vordere Oberschenkel.','1. Stange auf den vorderen Schultern. 2. Tief in die Hocke. 3. Hochdrücken.'),
  ('Hackenschmidt-Kniebeuge','intermediate','machine','legs','Geführte Kniebeuge an der Hack-Maschine.','1. Schultern an die Polster. 2. Tief beugen. 3. Hochdrücken.'),
  ('Gehende Ausfallschritte','intermediate','dumbbell','legs','Gehende Ausfallschritte für Beine und Gesäß.','1. Großer Schritt nach vorn. 2. Absenken. 3. Mit dem hinteren Bein nach vorn.'),
  ('Step-ups','beginner','dumbbell','legs','Aufsteigen auf eine Erhöhung.','1. Einen Fuß auf die Box. 2. Hochsteigen. 3. Kontrolliert absteigen, Seite wechseln.'),
  ('Wadenheben Beinpresse','beginner','machine','calves','Wadenheben an der Beinpresse.','1. Fußballen an die Platte. 2. Zehen wegdrücken. 3. Zurück.'),
  ('Wadenheben (Smith)','intermediate','machine','calves','Stehendes Wadenheben in der Smith-Maschine.','1. Stange auf den Schultern. 2. Auf die Zehen. 3. Senken.'),
  ('Seilspringen','beginner','bodyweight','calves','Seilspringen trainiert die Waden ausdauernd.','1. Seil schwingen. 2. Auf den Fußballen springen. 3. Rhythmus halten.'),
  ('Sumo-Kreuzheben','advanced','barbell','glutes','Kreuzheben mit breitem Stand, Gesäßfokus.','1. Breiter Stand, Stange greifen. 2. Mit geradem Rücken heben. 3. Absenken.'),
  ('Kabel-Durchzug (Pull Through)','intermediate','cable','glutes','Hüftstreckung am Kabel für das Gesäß.','1. Seil zwischen den Beinen. 2. Hüfte nach vorn strecken. 3. Zurück.'),
  ('Negativ-Liegestütze','intermediate','bodyweight','chest','Liegestütze mit erhöhten Füßen, betont die obere Brust.','1. Füße erhöht, Hände am Boden. 2. Körper gerade absenken. 3. Hochdrücken.'),
  ('Wand-Liegestütze','beginner','bodyweight','chest','Leichte Liegestütze im Stehen gegen die Wand.','1. Hände an die Wand. 2. Oberkörper zur Wand senken. 3. Wegdrücken.'),
  ('Handstand-Liegestütze','advanced','bodyweight','shoulders','Anspruchsvolle Schulterübung im Handstand.','1. Handstand an der Wand. 2. Kopf Richtung Boden senken. 3. Hochdrücken.'),
  ('Schattenboxen: Jab','beginner','bodyweight','shoulders','Gerade Schläge trainieren Schultern und Kondition.','1. Grundstellung einnehmen. 2. Führhand gerade vorstoßen. 3. Schnell zurückziehen.'),
  ('Schattenboxen: Haken','beginner','bodyweight','shoulders','Seitliche Schläge für Schultern und Rumpf.','1. Grundstellung einnehmen. 2. Haken seitlich schlagen. 3. Deckung zurück.'),
  ('Bizeps-Klimmzug','advanced','bodyweight','biceps','Klimmzug im Untergriff mit starkem Bizepsreiz.','1. Untergriff fassen. 2. Hochziehen bis Kinn über die Stange. 3. Absenken.'),
  ('Enge Bizeps-Klimmzüge','advanced','bodyweight','biceps','Klimmzüge mit engem Griff, maximale Bizepsspannung.','1. Enger Untergriff. 2. Hochziehen. 3. Kontrolliert absenken.'),
  ('Seitliches Bizeps-Curl (Eigengewicht)','beginner','bodyweight','biceps','Bizeps-Curl in Seitenlage gegen den eigenen Widerstand.','1. Seitlich liegen. 2. Unterarm gegen Widerstand curlen. 3. Senken.'),
  ('Trizeps-Dips (zwischen Bänken)','intermediate','bodyweight','triceps','Dips zwischen zwei Bänken für den Trizeps.','1. Hände auf einer Bank, Füße auf der anderen. 2. Absenken. 3. Hochdrücken.'),
  ('Bank-Dips (Knie gebeugt)','beginner','bodyweight','triceps','Leichte Bank-Dips mit angewinkelten Knien.','1. Hände auf der Bank, Knie gebeugt. 2. Körper absenken. 3. Hochdrücken.'),
  ('Sprungkniebeuge','intermediate','bodyweight','legs','Explosive Kniebeuge mit Strecksprung.','1. In die Hocke gehen. 2. Kräftig nach oben springen. 3. Weich landen.'),
  ('Sissy-Squat','advanced','bodyweight','legs','Kniebeuge mit zurückgelehntem Oberkörper, starker Quadrizepsreiz.','1. Auf den Zehen, Oberkörper zurücklehnen. 2. Knie nach vorn beugen. 3. Wieder aufrichten.'),
  ('Beinbeuger am Boden','intermediate','bodyweight','legs','Beinrückseite ohne Gerät über die Absenkphase.','1. Kniend, Füße fixiert. 2. Langsam nach vorn absenken. 3. Hochdrücken.'),
  ('Wadenheben auf der Treppe','beginner','bodyweight','calves','Wadenheben auf einer Stufe für mehr Bewegungsumfang.','1. Fußballen auf der Stufe. 2. Fersen heben. 3. Tief absenken.'),
  ('Hüftstrecken auf der Bank','beginner','bodyweight','glutes','Gesäß-Isolation, Bein von der Bank nach oben strecken.','1. Oberkörper auf der Bank. 2. Bein nach hinten/oben strecken. 3. Senken.'),
  ('Flutter Kicks','beginner','bodyweight','glutes','Schnelles Beinflattern für Gesäß und unteren Bauch.','1. Rückenlage, Beine gestreckt anheben. 2. Schnell auf und ab flattern. 3. Spannung halten.'),
  ('Knie-Liegestütze','beginner','bodyweight','chest','Leichte Liegestütze auf den Knien.','1. Auf den Knien abstützen. 2. Oberkörper absenken. 3. Hochdrücken.'),
  ('Isometrisches Brustdrücken','beginner','bodyweight','chest','Hände vor der Brust gegeneinander pressen.','1. Handflächen vor der Brust. 2. Fest zusammendrücken. 3. Spannung halten.'),
  ('Umgekehrtes Rudern','beginner','bodyweight','back','Rudern unter einer Stange mit dem Körpergewicht.','1. Unter der Stange liegen, fassen. 2. Brust zur Stange ziehen. 3. Absenken.'),
  ('Schulterblatt-Klimmzug','beginner','bodyweight','back','Aktiviert den oberen Rücken über die Schulterblätter.','1. An der Stange hängen. 2. Schulterblätter nach unten ziehen. 3. Lösen.'),
  ('Rückenstrecker am Boden','beginner','bodyweight','back','Stärkt den unteren Rücken am Boden.','1. Bauchlage. 2. Oberkörper leicht anheben. 3. Senken.'),
  ('Body-up','beginner','bodyweight','triceps','Trizeps-Drücken aus dem Unterarmstütz.','1. Unterarmstütz. 2. Auf die Hände hochdrücken. 3. Zurück.'),
  ('Trizeps-Dips am Boden','beginner','bodyweight','triceps','Dips am Boden für den Trizeps.','1. Hände hinter dem Körper am Boden. 2. Hüfte absenken. 3. Hochdrücken.'),
  ('Bank-Dips am Boden','beginner','bodyweight','triceps','Leichte Dips mit Händen am Boden.','1. Hände am Boden, Füße vorn. 2. Ellbogen beugen. 3. Strecken.'),
  ('Körpergewicht-Kniebeuge','beginner','bodyweight','legs','Kniebeuge nur mit dem eigenen Körpergewicht.','1. Schulterbreiter Stand. 2. Tief in die Hocke. 3. Hochkommen.'),
  ('Split Squats','beginner','bodyweight','legs','Statische Ausfallschritt-Kniebeuge.','1. Schrittstellung. 2. Hinteres Knie absenken. 3. Hochdrücken, Seite wechseln.'),
  ('Beinbeuger einbeinig (stehend)','beginner','bodyweight','legs','Beinrückseite einbeinig im Stehen.','1. Auf einem Bein stehen. 2. Ferse zum Gesäß ziehen. 3. Senken.'),
  ('Einbeiniges Wadenheben am Boden','beginner','bodyweight','calves','Wadenheben auf einem Bein, flach am Boden.','1. Auf einem Bein stehen. 2. Ferse heben. 3. Senken, Seite wechseln.'),
  ('Flache Gesäßbrücke am Boden','beginner','bodyweight','glutes','Leichte Gesäßbrücke flach am Boden.','1. Rückenlage, Knie gebeugt. 2. Hüfte leicht anheben. 3. Senken.'),
  ('Bizeps-Konzentration (Eigengewicht)','beginner','bodyweight','biceps','Bizeps-Curl gegen das eigene Bein als Widerstand.','1. Sitzend, Hand unter dem Knie. 2. Gegen Widerstand curlen. 3. Senken.'),
  ('Bizeps-Curl mit Theraband','beginner','bodyweight','biceps','Bizeps-Curl mit dem Theraband – ohne Gym, auch mit Wasserflaschen möglich.','1. Auf das Band treten, Enden greifen. 2. Hochcurlen. 3. Langsam senken.'),
  ('Konzentrationscurl mit Theraband','beginner','bodyweight','biceps','Isolierter Bizeps-Curl mit dem Band.','1. Band unter den Fuß, Ellbogen am Oberschenkel. 2. Hochcurlen. 3. Senken.'),
  ('Überkopf-Bizepscurl mit Theraband','beginner','bodyweight','biceps','Einarmiger Bizepscurl mit dem Band.','1. Band fixieren, Arm seitlich anheben. 2. Hand Richtung Kopf curlen. 3. Strecken.'),
  ('Seitheben mit Theraband','beginner','bodyweight','shoulders','Seitheben mit dem Theraband – ohne Gym, auch mit Wasserflaschen möglich.','1. Auf das Band treten, Enden greifen. 2. Arme zur Seite heben. 3. Senken.'),
  ('Frontheben mit Theraband','beginner','bodyweight','shoulders','Frontheben mit dem Band für die vordere Schulter.','1. Auf das Band treten, Enden greifen. 2. Arme nach vorn heben. 3. Senken.'),
  ('Schulterdrücken mit Theraband','beginner','bodyweight','shoulders','Schulterdrücken mit dem Band über Kopf.','1. Band unter die Füße, Enden auf Schulterhöhe. 2. Über Kopf drücken. 3. Senken.')
) as e(name, difficulty, equipment, muscle_key, description, instructions)
join public.muscles m on m.key = e.muscle_key
where not exists (select 1 from public.exercises x where x.name = e.name);
