-- ============================================================================
--  Migration 032 - Maximale Uebungs-Erweiterung (auto-generiert aus ExerciseDB)
--  Alle GIF-IDs sind gegen die App-API verifiziert -> GIFs funktionieren.
--  GIFs werden client-seitig ueber app/lib/exerciseMedia.ts per NAME aufgeloest.
--  Im SQL Editor mit KORREKTER UTF-8-Kodierung einspielen. Idempotent.
-- ============================================================================
insert into public.exercises (name, difficulty, equipment, primary_muscle_id, description, instructions)
select e.name, e.difficulty, e.equipment, m.id, e.description, e.instructions
from (values
  ('Wechselnd Latzug','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Assistierte Sit-Up','beginner','machine','abs','Maschine-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Assistierte Stehend Klimmzug-Untergriff','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Assistierte Stehend Klimmzug','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Assistierte Klimmzug','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Bankdrücken','intermediate','other','chest','Gerät-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Band Eng Latzug','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Eng Liegestütze','intermediate','other','triceps','Gerät-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Band Kniend Einarmig Latzug','advanced','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Kniend Drehend Crunch','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Band Einarmig Einbeinig Split-Squat','advanced','other','legs','Gerät-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Band Einarmig Stehend Tief Rudern','advanced','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Einarmig Drehend Brust Drücken','advanced','other','chest','Gerät-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Band Einarmig Drehend Sitzendes Rudern','advanced','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Durchzug','intermediate','other','glutes','Gerät-Übung für das Gesäß.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Push Sit-Up','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Band Sitzend Twist','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Band Shrugs','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Band Einbeinig Umgekehrt Wadenheben','advanced','other','calves','Gerät-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Band Einbeinig Split-Squat','advanced','other','legs','Gerät-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Band Kniebeuge','intermediate','other','glutes','Gerät-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Band Stehend Crunch','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Band Stehend Drehend Crunch','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Band Gestrecktes Kreuzheben','intermediate','other','glutes','Gerät-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Band Drehend Schulterdrücken','intermediate','other','shoulders','Gerät-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Wechselnd Bizeps Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Enges Bankdrücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Negativ Überzug','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Negativ Breit Drücken','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Negativ Breit Überzug','intermediate','barbell','back','Langhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Frontheben','intermediate','barbell','shoulders','Langhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Langhantel Hack-Kniebeuge','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Hoch Stange Kniebeuge','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Schräg Enges Bankdrücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Schräg Umgekehrt Drücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Schräg Rudern','intermediate','barbell','back','Langhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Schräg Schulter Heben','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Langhantel Tief Stange Kniebeuge','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Liegend Eng Drücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Liegend Eng Trizepsstrecken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Langhantel Liegend Strecken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Langhantel Liegend Scott-Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Liegende Trizepsstrecken Stirndrücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Einarmig Vorgebeugtes Rudern','advanced','barbell','back','Langhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Einarmig Bodendrücken','advanced','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Einbeinig Kniebeuge','advanced','barbell','legs','Langhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Überkopf-Kniebeuge','intermediate','barbell','legs','Langhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Scott-Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Schräg-Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Überzug','intermediate','barbell','back','Langhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Ausfallschritt-Rückwärts','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Umgekehrt Enges Bankdrücken','intermediate','barbell','triceps','Langhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Umgekehrt Negativ-Bankdrücken','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Umgekehrt Schrägbankdrücken','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Umgekehrt Scott-Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Sitzend Wadenheben','intermediate','barbell','calves','Langhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Langhantel Sitzend Eng Konzentrationscurls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Sitzend Good-Morning','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Langhantel Sitzend Schulterdrücken','intermediate','barbell','shoulders','Langhantel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Sitzend Twist','intermediate','barbell','abs','Langhantel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Langhantel Einbeinig Split-Squat','advanced','barbell','legs','Langhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Split-Squat','intermediate','barbell','legs','Langhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Stehend Wadenheben','intermediate','barbell','calves','Langhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Langhantel Stehend Eng Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Stehend Eng Schulterdrücken','intermediate','barbell','shoulders','Langhantel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Stehend Konzentrationscurls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Stehend Umgekehrt Curls','intermediate','barbell','biceps','Langhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Langhantel Stehend Twist','intermediate','barbell','abs','Langhantel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Langhantel Step-Up','intermediate','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Gestrecktes Kreuzheben','intermediate','barbell','legs','Langhantel-Übung für die Beine.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Langhantel Aufrechtes Rudern','intermediate','barbell','shoulders','Langhantel-Übung für die Schulter.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Breit Umgekehrt Bankdrücken','intermediate','barbell','chest','Langhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Langhantel Breit Kniebeuge','intermediate','barbell','legs','Langhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Langhantel Breit Aufrechtes Rudern','intermediate','barbell','shoulders','Langhantel-Übung für die Schulter.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Langhantel Zercher Kniebeuge','advanced','barbell','glutes','Langhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Vorgebeugt Knie Liegend Twist','beginner','bodyweight','glutes','Körpergewicht-Übung für das Gesäß.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Wechselnd Schulterdrücken','beginner','cable','shoulders','Kabel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Wechselnd Trizepsstrecken','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Stange Latzug','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Bankdrücken','beginner','cable','chest','Kabel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Eng Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Konzentrationscurls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Kreuzheben','beginner','cable','glutes','Kabel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Kabel Negativ Fliegende','beginner','cable','chest','Kabel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Negativ Einarmig Drücken','advanced','cable','chest','Kabel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Negativ Drücken','beginner','cable','chest','Kabel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Negativ Sitzend Breit Rudern','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Drag-Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Boden Sitzend Breit Rudern','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Hoch Rudern Kniend','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Schräg Trizepsstrecken','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Kniend Crunch','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Kniend Trizepsstrecken','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Tief Sitzendes Rudern','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Liegend Bizeps Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Liegend Eng Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Liegend Fliegende','beginner','cable','chest','Kabel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Liegende Trizepsstrecken','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Einarmig Vorgebeugtes Rudern','advanced','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Einarmig Negativ Brust Fliegende','advanced','cable','chest','Kabel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Einarmig Schräg Drücken','advanced','cable','chest','Kabel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Einarmig Scott-Curls','advanced','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Einarmig Latzug','advanced','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Einarmig Umgekehrt Scott-Curls','advanced','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Latzug','beginner','cable','back','Kabel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kabel Latzug Bizeps Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Umgekehrt Crunch','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Reverse-Curls','beginner','cable','biceps','Kabel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kabel Umgekehrt Pushdown','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Seil Schräg Trizepsstrecken','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Sitzend Brust Drücken','beginner','cable','chest','Kabel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Sitzend Crunch','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Sitzend Twist','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Schulterdrücken','beginner','cable','shoulders','Kabel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kabel Stehend Wadenheben','beginner','cable','calves','Kabel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Stehend Crunch','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kabel Stehend Fliegende','beginner','cable','chest','Kabel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Stehend Einarmig Trizepsstrecken','advanced','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Stehend Einbeinig Wadenheben','advanced','cable','calves','Kabel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kabel Stehend Umgekehrt Einarmig Überkopf Trizepsstrecken','advanced','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Trizeps-Pushdown Stange','beginner','cable','triceps','Kabel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kabel Twist','beginner','cable','abs','Kabel-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Eng Klimmzug-Untergriff','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Crunch Boden','beginner','bodyweight','abs','Körpergewicht-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Negativ Sit-Up','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Wechselnd Bizeps Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Wechselnd Hammer Scott-Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Wechselnd Scott-Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Wechselnd Sitzend Hammer-Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Arnold-Press','intermediate','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Vorgebeugtes Rudern','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Bizeps Curls Umgekehrt','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Bizeps Curls Kniebeuge','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Eng Drücken','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Konzentrationscurls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Kreuzheben','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Kurzhantel Negativ-Bankdrücken','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Negativ Fliegende','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Negativ Hammer Drücken','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Negativ Einarmig Fliegende','advanced','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Negativ Einarmig Hammer Drücken','advanced','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Negativ Shrugs','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Negativ Trizepsstrecken','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Negativ Twist Fliegende','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Frontheben','intermediate','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Hammer-Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Hoch Curls','intermediate','dumbbell','biceps','Kurzhantel-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Kurzhantel Schräg Wechselnd Drücken','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Schräg Fliegende','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Schräg Hammer Drücken','intermediate','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Schräg Einarmig Fliegende','advanced','dumbbell','chest','Kurzhantel-Übung für die Brust.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Schräg Einarmig Hammer Drücken','advanced','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Schräg Einarmig Seitheben','advanced','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Schräg Heben','intermediate','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Schräg Shrugs','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Schräg T Heben','intermediate','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Schräg Trizepsstrecken','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Kickback','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Seitheben','intermediate','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Ausfallschritt','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Liegend Wechselnd Strecken','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Einarmig Vorgebeugtes Rudern','advanced','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Einarmig Kickback','advanced','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Einarmig Seitheben','advanced','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Einarmig Schulterdrücken','advanced','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kurzhantel Einarmig Aufrechtes Rudern','advanced','dumbbell','shoulders','Kurzhantel-Übung für die Schulter.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Ausfallschritt-Rückwärts','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Umgekehrt Rudern','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Rumänisches-Kreuzheben','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Kurzhantel Sitzend Kickback','intermediate','dumbbell','triceps','Kurzhantel-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Kurzhantel Sitzend Einbeinig Wadenheben','advanced','dumbbell','calves','Kurzhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Sitzend Einbeinig Wadenheben Hammer','advanced','dumbbell','calves','Kurzhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Shrugs','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kurzhantel Einbeinig Wadenheben','advanced','dumbbell','calves','Kurzhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Einbeinig Kreuzheben','advanced','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Kurzhantel Einbeinig Split-Squat','advanced','dumbbell','legs','Kurzhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Einbeinig Kniebeuge','advanced','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Kniebeuge','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Stehend Wadenheben','intermediate','dumbbell','calves','Kurzhantel-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Kurzhantel Step-Up','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Step-Up Ausfallschritt','intermediate','dumbbell','legs','Kurzhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Step-Up Split-Squat','intermediate','dumbbell','legs','Kurzhantel-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Kurzhantel Gestrecktes Kreuzheben','intermediate','dumbbell','glutes','Kurzhantel-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('SZ-Stangen Stange Umgekehrt Vorgebeugtes Rudern','intermediate','barbell','back','Langhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Hüfte Heben Vorgebeugt Knie','beginner','bodyweight','abs','Körpergewicht-Übung für den Bauch.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Schräg Umgekehrt Liegestütze','intermediate','other','chest','Gerät-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Schräg Drehend Sit-Up','intermediate','other','abs','Gerät-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Kettlebell Wechselnd Rudern','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kettlebell Vorgebeugt Drücken','intermediate','dumbbell','abs','Kurzhantel-Übung für den Bauch.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Kettlebell Einarmig Rudern','advanced','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Kettlebell Sumo Hoch Pull','intermediate','dumbbell','back','Kurzhantel-Übung für den Rücken.','1. Saubere Ausgangsposition. 2. Bewegung kontrolliert und mit voller Amplitude ausführen. 3. Langsam zurück.'),
  ('Liegestütze Wand','beginner','bodyweight','chest','Körpergewicht-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Heben Einarmig Liegestütze','advanced','bodyweight','chest','Körpergewicht-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Umgekehrt Maschine Latzug','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Umgekehrt Klimmzug','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Sitzend Beinheben','beginner','bodyweight','abs','Körpergewicht-Übung für den Bauch.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Schulter Klimmzug','intermediate','other','back','Gerät-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Sit-Up','beginner','bodyweight','abs','Körpergewicht-Übung für den Bauch.','1. Rumpf bewusst anspannen. 2. Bewegung sauber ausführen. 3. Kontrolliert zurück.'),
  ('Smith Rücken Shrugs','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Bankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Vorgebeugt Knie Good-Morning','beginner','machine','glutes','Maschine-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Smith Vorgebeugtes Rudern','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Kreuzheben','beginner','machine','glutes','Maschine-Übung für das Gesäß.','1. Hüfte gebeugt, Rücken gerade. 2. Mit Hüfte/Beinen aufrichten. 3. Kontrolliert absenken.'),
  ('Smith Negativ-Bankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Negativ Umgekehrt Drücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Hack-Kniebeuge','beginner','machine','glutes','Maschine-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Smith Hüfte Heben','beginner','machine','abs','Maschine-Übung für den Bauch.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Smith Schrägbankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Schräg Umgekehrt Drücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Tief Stange Kniebeuge','beginner','machine','glutes','Maschine-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Smith Maschine Bizeps Curls','beginner','machine','biceps','Maschine-Übung für den Bizeps.','1. Arme gestreckt, Ellbogen am Körper. 2. Gewicht nach oben curlen. 3. Langsam absenken.'),
  ('Smith Maschine Negativ Enges Bankdrücken','beginner','machine','triceps','Maschine-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Maschine Schräg Trizepsstrecken','beginner','machine','triceps','Maschine-Übung für den Trizeps.','1. Ellbogen fixieren. 2. Vollständig strecken. 3. Kontrolliert beugen.'),
  ('Smith Maschine Umgekehrt Negativ Enges Bankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Eng Rudern','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Einarmig Rudern','advanced','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Einbeinig Boden Wadenheben','advanced','machine','calves','Maschine-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Smith Umgekehrt Vorgebeugtes Rudern','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Umgekehrt Drücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Sitzend Einbeinig Wadenheben','advanced','machine','calves','Maschine-Übung für die Waden.','1. Aufrecht/stabil, Arme leicht gebeugt. 2. Kontrolliert anheben/zusammenführen. 3. Langsam senken.'),
  ('Smith Sitzend Schulterdrücken','beginner','machine','shoulders','Maschine-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Schulterdrücken','beginner','machine','shoulders','Maschine-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Shrugs','beginner','machine','back','Maschine-Übung für den Rücken.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Einbeinig Split-Squat','advanced','machine','legs','Maschine-Übung für die Beine.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Smith Kniebeuge','beginner','machine','glutes','Maschine-Übung für das Gesäß.','1. Stabiler Stand. 2. Kontrolliert absenken. 3. Kräftig hochdrücken.'),
  ('Smith Stehend Schulterdrücken','beginner','machine','shoulders','Maschine-Übung für die Schulter.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Aufrechtes Rudern','beginner','machine','shoulders','Maschine-Übung für die Schulter.','1. Stabile Position, Rücken gerade. 2. Gewicht zum Körper ziehen, Schulterblätter zusammen. 3. Kontrolliert zurück.'),
  ('Smith Breites Bankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Smith Breit Negativ-Bankdrücken','beginner','machine','chest','Maschine-Übung für die Brust.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.'),
  ('Trizeps Drücken','beginner','bodyweight','triceps','Körpergewicht-Übung für den Trizeps.','1. Stabile Ausgangsposition einnehmen. 2. Gewicht/Körper kontrolliert wegdrücken. 3. Langsam zurückführen.')
) as e(name, difficulty, equipment, muscle_key, description, instructions)
join public.muscles m on m.key = e.muscle_key
where not exists (select 1 from public.exercises x where x.name = e.name);
